export const SHIP_COUNTRIES = [
  { name: 'Germany', group: 'DE' },
  { name: 'United Kingdom', group: 'UK' },
  { name: 'Austria', group: 'EU' },
  { name: 'Belgium', group: 'EU' },
  { name: 'Bulgaria', group: 'EU' },
  { name: 'Croatia', group: 'EU' },
  { name: 'Cyprus', group: 'EU' },
  { name: 'Czech Republic', group: 'EU' },
  { name: 'Denmark', group: 'EU' },
  { name: 'Estonia', group: 'EU' },
  { name: 'Finland', group: 'EU' },
  { name: 'France', group: 'EU' },
  { name: 'Greece', group: 'EU' },
  { name: 'Hungary', group: 'EU' },
  { name: 'Ireland', group: 'EU' },
  { name: 'Italy', group: 'EU' },
  { name: 'Latvia', group: 'EU' },
  { name: 'Lithuania', group: 'EU' },
  { name: 'Luxembourg', group: 'EU' },
  { name: 'Malta', group: 'EU' },
  { name: 'Netherlands', group: 'EU' },
  { name: 'Poland', group: 'EU' },
  { name: 'Portugal', group: 'EU' },
  { name: 'Romania', group: 'EU' },
  { name: 'Slovakia', group: 'EU' },
  { name: 'Slovenia', group: 'EU' },
  { name: 'Spain', group: 'EU' },
  { name: 'Sweden', group: 'EU' },
  { name: 'Switzerland', group: 'EU' },
  { name: 'Norway', group: 'EU' },
  { name: 'United States', group: 'ROW' },
  { name: 'Canada', group: 'ROW' },
  { name: 'Australia', group: 'ROW' },
  { name: 'Other', group: 'ROW' }
];
